version: '3'
services:
  mugalim-frontend:
    build: .                   # указываем, что сборка идет из текущей директории
    ports:
      - "6905:80"              # пробрасываем порт 80 контейнера на 6905 внешнего сервера
    restart: always            # автоматически перезапускает контейнер при сбоях
