export { default as Home } from './home/Home'
export { default as Login } from './login/Login'
export { default as Signup } from './signup/Signup'
export { default as Welcome } from './welcom/Welcom'
export { default as Notfond } from './notfound/Notfound'